"""Update product images structure

Revision ID: f6cb749a5e59
Revises: d0d6f0369cd4
Create Date: 2026-06-23 15:41:33.713847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6cb749a5e59'
down_revision = 'd0d6f0369cd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('image_url', sa.String(length=500), nullable=True))

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thumbnail_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('main_image_url', sa.String(length=500), nullable=True))
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.drop_column('main_image_url')
        batch_op.drop_column('thumbnail_url')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_column('image_url')
        batch_op.drop_column('description')

    op.drop_table('product_images')
    # ### end Alembic commands ###
