name: Build and deploy Flask backend to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Check backend dependencies
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_DCA9EF02695A4F228E2139B39708EA19 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_963597E707C8445FBE95C4FF60D76BB3 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_BC52A648988947BC814AA8C955C07B65 }}

      - name: Deploy backend to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "EcommerceSite"
          slot-name: "Production"
          package: "./backend"
